SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A JOIN BOOK_SALES S ON B.AUTHOR_ID=A.AUTHOR_ID AND B.BOOK_ID=S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01-%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC