WITH A AS (SELECT CART_ID, GROUP_CONCAT(DISTINCT NAME) AS NAME_LIST
     FROM CART_PRODUCTS
     GROUP BY CART_ID)

SELECT CART_ID
FROM A
WHERE NAME_LIST LIKE '%Yogurt%' AND NAME_LIST LIKE '%Milk%'
ORDER BY CART_ID
