SELECT I.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO I JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) B USING(FOOD_TYPE)
WHERE FAVORITES=MAX_FAVORITES
ORDER BY I.FOOD_TYPE DESC