WITH A AS (SELECT CAR_ID, 
       CASE WHEN END_DATE >= '2022-10-16' AND START_DATE<='2022-10-16'
            THEN 1
            ELSE 0 END AS AVAILABILITY, START_DATE, END_DATE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, CASE WHEN SUM(AVAILABILITY)=0 THEN '대여 가능'
                    ELSE '대여중' END AS AVAILABILITY
FROM A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC