WITH A AS(SELECT F.FLAVOR, F.TOTAL_ORDER AS F_TOTAL, SUM(J.TOTAL_ORDER) AS J_TOTAL
          FROM FIRST_HALF F JOIN JULY J USING(FLAVOR)
          GROUP BY FLAVOR)

SELECT FLAVOR
FROM A
ORDER BY F_TOTAL+J_TOTAL DESC
LIMIT 3