WITH RECURSIVE TIME as (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME WHERE HOUR<23)

SELECT T.HOUR as HOUR, COUNT(ANIMAL_ID) as COUNT
FROM ANIMAL_OUTS O RIGHT JOIN TIME T
ON HOUR(O.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY HOUR