WITH A AS (SELECT M.MEMBER_ID, COUNT(REVIEW_ID) AS N_RE
           FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING(MEMBER_ID)
           GROUP BY M.MEMBER_ID
           ORDER BY N_RE DESC
           LIMIT 1)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R USING(MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID FROM A)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC