WITH A AS (SELECT *
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
           WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'),
     B AS (SELECT CAR_ID, COUNT(HISTORY_ID) AS RECORDS
           FROM A
           GROUP BY CAR_ID
           HAVING RECORDS >=5
           ORDER BY CAR_ID DESC)

SELECT MONTH(START_DATE), CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM A
WHERE CAR_ID IN (SELECT CAR_ID FROM B)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC