SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_L
                     FROM FISH_INFO
                     GROUP BY FISH_TYPE
                     HAVING COUNT(ID)>1) B JOIN FISH_NAME_INFO C
    ON A.FISH_TYPE=B.FISH_TYPE AND B.FISH_TYPE=C.FISH_TYPE
WHERE LENGTH=MAX_L
ORDER BY ID