SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT JOIN 
    (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) A
    USING(CATEGORY)
WHERE CATEGORY IN ('과자','국','김치','식용유')
      AND MAX_PRICE=PRICE
ORDER BY PRICE DESC